"""
V2 Graph Nodes
Implementation of Iteration 1: The "Dumb" Loop with domain-specific agents
"""

from typing import Any, Dict, List
from consensus.v2.state import ResearchState, AgentConfig
from consensus.models.llm_client import LLMClient


# Iteration 1: Hardcoded agents (commented out for reference)
# Iteration 2: Agents are dynamically generated by Orchestrator based on topic

# System prompt template for dynamic team generation
TEAM_GENERATION_PROMPT = """You are an expert Project Manager and Domain Analyst.

Analyze the following research topic and determine what expert perspectives are needed for a comprehensive analysis:

TOPIC: "{topic}"

Your task:
1. Identify the primary domain(s) of this topic (e.g., Economics, Technology, Healthcare, Policy, etc.)
2. Determine 3-5 distinct expert roles needed to fully assess this topic from multiple angles
3. Include at least one "Skeptic" or "Risk Analyst" role for critical perspective
4. Ensure roles are domain-specific and complementary

For each role, provide:
- role: The expert title (e.g., "Labor Economist", "Sustainability Consultant")
- domain: The field of expertise (e.g., "Economics", "Environmental Science")
- goal: Specific objective for this research (1 sentence)

Output ONLY a valid JSON array. Example format:
[
  {{"role": "Labor Economist", "domain": "Economics", "goal": "Analyze workforce demographics and labor market trends"}},
  {{"role": "Sociologist", "domain": "Sociology", "goal": "Examine social structures and cultural implications"}},
  {{"role": "Policy Analyst", "domain": "Public Policy", "goal": "Evaluate regulatory frameworks and implementation challenges"}},
  {{"role": "Skeptic", "domain": "Risk Analysis", "goal": "Challenge assumptions and identify potential risks"}}
]

JSON Output:"""


class OrchestratorNode:
    """Orchestrator node - manages the research workflow"""
    
    def __init__(self, llm_client: LLMClient):
        self.llm_client = llm_client
    
    async def propose_team(self, state: ResearchState) -> Dict[str, Any]:
        """
        Propose a team of agents for the research topic.
        Iteration 2: Uses LLM to dynamically generate domain-specific team.
        """
        print(f"\n[Orchestrator] Analyzing topic: {state.topic}")
        print("[Orchestrator] Generating domain-specific team via LLM...")
        
        # Generate team using LLM
        prompt = TEAM_GENERATION_PROMPT.format(topic=state.topic)
        
        # Get model from config for team generation
        model_config = state.config.get("models", {})
        default_model = model_config.get("default_model", "gpt-4o")
        
        response = await self.llm_client.complete(
            prompt=prompt,
            model=default_model,  # Use configured model
            temperature=0.7,
            max_tokens=1500
        )
        
        # Parse JSON response
        import json
        try:
            # Extract JSON from response (handle potential markdown code blocks)
            json_str = response
            if "```json" in response:
                json_str = response.split("```json")[1].split("```")[0].strip()
            elif "```" in response:
                json_str = response.split("```")[1].split("```")[0].strip()
            
            team_data = json.loads(json_str)
            
            if not isinstance(team_data, list):
                raise ValueError("Expected JSON array of agents")
            
        except (json.JSONDecodeError, ValueError) as e:
            print(f"[Orchestrator] Warning: Failed to parse LLM response, using fallback. Error: {e}")
            # Fallback to default team
            team_data = [
                {"role": "Domain Expert", "domain": "General Analysis", "goal": "Provide comprehensive analysis"},
                {"role": "Skeptic", "domain": "Critical Analysis", "goal": "Challenge assumptions and identify risks"}
            ]
        
        # Convert to AgentConfig objects with generated system prompts
        team = []
        for agent_data in team_data:
            role = agent_data.get("role", "Expert")
            domain = agent_data.get("domain", "General")
            goal = agent_data.get("goal", "Analyze the topic")
            
            # Generate system prompt for this role
            system_prompt = self._generate_system_prompt(role, domain, goal)
            
            # Get model from config (default_model or specific agent config)
            model_config = state.config.get("models", {})
            default_model = model_config.get("default_model", "gpt-4o")
            
            team.append(AgentConfig(
                role=role,
                domain=domain,
                goal=goal,
                system_prompt=system_prompt,
                model=default_model,
                temperature=0.6 if "skeptic" not in role.lower() else 0.8
            ))
        
        print(f"[Orchestrator] Generated team: {', '.join(a.role for a in team)}")
        
        return {
            "team_manifest": team,
            "status": "planning",
        }
    
    def _generate_system_prompt(self, role: str, domain: str, goal: str) -> str:
        """Generate a system prompt for an agent based on its configuration."""
        return f"""You are a {role} specializing in {domain}.

Your Goal: {goal}

Expertise Guidelines:
1. Focus STRICTLY on aspects within your {domain} expertise
2. Use domain-specific frameworks, terminology, and analytical approaches
3. Consider both theoretical and practical implications
4. Be precise and evidence-based in your reasoning
5. Acknowledge limitations of your perspective when appropriate

When analyzing a topic:
- Provide 2-3 concise paragraphs of analysis
- Stay within your domain expertise
- Avoid generalizations outside your field
- Highlight domain-specific implications

Respond as a {role} would, with appropriate depth and perspective."""
    
    async def evaluate_consensus(self, state: ResearchState) -> Dict[str, Any]:
        """
        Evaluate if consensus has been reached among agents.
        Simple implementation - increments iteration and checks if done.
        """
        # Increment iteration counter
        new_iteration = state.current_iteration + 1
        print(f"\n[Orchestrator] Evaluating consensus (iteration {new_iteration})...")
        
        # Simple logic: stop after 1 iteration (for testing)
        # In Iteration 4, this will use LLM to analyze conflicts and consensus
        if new_iteration >= 1:
            print("[Orchestrator] Consensus evaluation: Sufficient iterations completed")
            return {
                "current_iteration": new_iteration,
                "consensus_status": "REACHED",
                "consensus_score": 0.75,
                "status": "completed",
            }
        
        return {
            "current_iteration": new_iteration,
            "consensus_status": "IN_PROGRESS",
            "consensus_score": 0.5,
            "status": "debating",
        }


class AgentNode:
    """Generic agent node that adapts based on agent configuration"""
    
    def __init__(self, llm_client: LLMClient, agent_config: AgentConfig):
        self.llm_client = llm_client
        self.config = agent_config
    
    async def research(self, state: ResearchState) -> Dict[str, Any]:
        """
        Conduct initial research on the topic.
        """
        print(f"\n  [{self.config.role}] Researching...")
        
        # Build prompt with context
        prompt = f"""Topic: {state.topic}

Your Role: {self.config.role}
Your Domain: {self.config.domain}
Your Goal: {self.config.goal}

Provide your expert analysis of this topic from your specific domain perspective.
Focus only on aspects within your expertise. Be concise but thorough."""
        
        # Call LLM
        response = await self.llm_client.complete(
            prompt=prompt,
            system_prompt=self.config.system_prompt,
            model=self.config.model,
            temperature=self.config.temperature,
            max_tokens=800
        )
        
        # Store output in state
        output_key = self.config.role
        print(f"  [{self.config.role}] Analysis complete ({len(response)} chars)")
        
        return {
            "agent_outputs": {output_key: response}
        }
    
    async def critique(self, state: ResearchState, target_role: str) -> Dict[str, Any]:
        """
        Critique another agent's output.
        """
        target_output = state.get_agent_output(target_role)
        if not target_output:
            return {"agent_outputs": {}}
        
        print(f"\n  [{self.config.role}] Critiquing {target_role}...")
        
        prompt = f"""Topic: {state.topic}

You are reviewing the analysis from a {target_role}.

Their Analysis:
{target_output}

Your Role: {self.config.role} ({self.config.domain})
Your Goal: {self.config.goal}

Provide your critique of their analysis from your domain perspective.
Identify gaps, challenge assumptions, or offer complementary insights.
Be specific and constructive."""
        
        response = await self.llm_client.complete(
            prompt=prompt,
            system_prompt=self.config.system_prompt,
            model=self.config.model,
            temperature=self.config.temperature,
            max_tokens=600
        )
        
        # Store critique with key indicating source and target
        output_key = f"{self.config.role}_critique_of_{target_role}"
        print(f"  [{self.config.role}] Critique complete ({len(response)} chars)")
        
        return {
            "agent_outputs": {output_key: response}
        }


class SynthesisNode:
    """Synthesizes agent outputs into final report"""
    
    def __init__(self, llm_client: LLMClient):
        self.llm_client = llm_client
    
    async def generate_report(self, state: ResearchState) -> Dict[str, Any]:
        """Generate final markdown report from agent outputs"""
        print("\n[Synthesizer] Generating final report...")
        
        # Build report content
        lines = [
            f"# Research Report: {state.topic}",
            "",
            "## Executive Summary",
            "",
            f"This research analyzed '{state.topic}' from multiple domain perspectives.",
            f"Consensus status: {state.consensus_status}",
            "",
            "## Expert Perspectives",
            "",
        ]
        
        # Add each agent's output
        for role, output in state.agent_outputs.items():
            if "critique" not in role:
                lines.append(f"### {role}")
                lines.append("")
                lines.append(output)
                lines.append("")
        
        # Add critique section if present
        critiques = {k: v for k, v in state.agent_outputs.items() if "critique" in k}
        if critiques:
            lines.append("## Critical Analysis")
            lines.append("")
            for role, output in critiques.items():
                # Parse role_from_critique_of_role format
                parts = role.replace("_critique_of_", " → ").replace("_", " ")
                lines.append(f"### {parts}")
                lines.append("")
                lines.append(output)
                lines.append("")
        
        # Add debate history
        if state.debate_history:
            lines.append("## Debate Log")
            lines.append("")
            for entry in state.debate_history:
                to_str = f" to {entry['to']}" if entry['to'] else ""
                lines.append(f"- **{entry['from']}{to_str}** ({entry['type']}): {entry['message'][:100]}...")
            lines.append("")
        
        report_content = "\n".join(lines)
        
        print(f"[Synthesizer] Report generated ({len(report_content)} chars)")
        
        return {
            "status": "completed",
            "end_time": __import__('datetime').datetime.now().isoformat(),
        }
