"""
V2 State Definition
Flexible state schema supporting dynamic agent outputs
"""

import re
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, field_validator
from datetime import datetime


def sanitize_identifier(name: str) -> str:
    """
    Sanitize a name to be a valid identifier.
    Only allows letters, numbers, underscores, and hyphens.
    Must not begin with a number.
    """
    # Convert to lowercase and replace spaces with hyphens
    safe = name.lower().replace(' ', '-')
    # Remove all characters except letters, numbers, underscores, hyphens
    safe = re.sub(r'[^a-z0-9_-]', '', safe)
    # Ensure doesn't start with a number
    if safe and safe[0].isdigit():
        safe = 'agent-' + safe
    return safe


class AgentConfig(BaseModel):
    """Configuration for a dynamically spawned agent"""
    role: str
    domain: str
    goal: str
    system_prompt: str = ""
    provider: str = ""
    model: str = "gpt-4o"
    temperature: float = 0.7
    search_enabled: bool = False
    
    @field_validator('role')
    @classmethod
    def sanitize_role(cls, v: str) -> str:
        """Sanitize role to valid identifier characters only."""
        return sanitize_identifier(v)


class ResearchState(BaseModel):
    """
    V2 State object for the research workflow.
    Supports dynamic team spawning with flexible agent_outputs dict.
    """
    # Topic and configuration
    topic: str = ""
    config: Dict[str, Any] = Field(default_factory=dict)
    
    # Team manifest - dynamically generated by Orchestrator
    # Can change between iterations
    team_manifest: List[AgentConfig] = Field(default_factory=list)
    team_approved: bool = False
    
    # Agent outputs - flexible dict keyed by agent role
    # Example: {"Labor Economist": "Analysis text...", "Sociologist": "Critique text..."}
    agent_outputs: Dict[str, str] = Field(default_factory=dict)
    
    # Executive summaries for UI display - keyed by agent role
    # Example: {"Labor Economist": "AI will likely displace routine jobs but create new opportunities..."}
    agent_summaries: Dict[str, str] = Field(default_factory=dict)
    
    # Phase 2: Orchestrator draft report - comprehensive structured document
    draft_report: str = ""
    
    # Phase 3: Critiques of the draft report
    draft_critiques: Dict[str, str] = Field(default_factory=dict)
    
    # Actionable summaries from critiques for UI display - keyed by agent role
    critique_summaries: Dict[str, str] = Field(default_factory=dict)
    
    # Final report generated by Synthesizer agent
    final_report: str = ""
    
    # Debate history - chronological log of interactions
    debate_history: List[Dict[str, Any]] = Field(default_factory=list)
    
    # Iteration tracking
    current_iteration: int = 0
    max_iterations: int = 5
    min_iterations: int = 1
    
    # Consensus tracking
    consensus_status: str = "IN_PROGRESS"  # IN_PROGRESS, REACHED, FAILED
    consensus_score: float = 0.0
    
    # Workflow status
    status: str = "initialized"  # initialized, planning, researching, critiquing, evaluating, completed, failed
    error: Optional[str] = None
    
    # Metadata
    start_time: Optional[str] = None
    end_time: Optional[str] = None
    
    def get_agent_output(self, role: str) -> str:
        """Get output from a specific agent by role"""
        return self.agent_outputs.get(role, "")
    
    def set_agent_output(self, role: str, output: str):
        """Set output for a specific agent by role"""
        self.agent_outputs[role] = output
    
    def add_debate_entry(self, from_role: str, to_role: Optional[str], 
                         message: str, entry_type: str = "critique"):
        """Add an entry to the debate history"""
        self.debate_history.append({
            "iteration": self.current_iteration,
            "from": from_role,
            "to": to_role,
            "type": entry_type,
            "message": message,
            "timestamp": datetime.now().isoformat()
        })
    
    def get_state_summary(self) -> Dict[str, Any]:
        """Get a summary of the current state for display"""
        return {
            "topic": self.topic,
            "status": self.status,
            "iteration": self.current_iteration,
            "agents": [a.role for a in self.team_manifest],
            "agent_outputs": list(self.agent_outputs.keys()),
            "consensus_status": self.consensus_status,
            "consensus_score": self.consensus_score,
        }
